spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mysql://az-container-mysql.mysql.database.azure.com:3306/defaultdb'
    username: managediduser
  sql:
    init:
      mode: always
      schema-locations: classpath:azuredatabaseschema.sql
  