name: Staging Release(Part 2)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["**"]

jobs:
  push_image:

    runs-on: ubuntu-20.04
    environment: az-container-book-environment
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up JDK 17 #
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build & Push Image #
        run: |
          az config set defaults.acr=azcontainerbookacr
          az acr login
          mvn compile com.google.cloud.tools:jib-maven-plugin:3.2.1:build \
            -Djib.from.image=eclipse-temurin:17.0.4_8-jre-alpine \
            -Djib.to.image=azcontainerbookacr.azurecr.io/todolist \
            -Djib.to.tags=v1.0.0-tem_17.0.4_8-jre-alpine_$GITHUB_SHA,latest \
            -Djib.container.endpoint=sh,webapp_startup.sh \
            -Djib.container.port=8080,2222 \
            -Djib.container.environment=JDK_JAVA_OPTIONS="-Xmx512m -XX:StartFlightRecording"

      - name: Update Staging Slot with the Latest Image #
        run: |
          az webapp config container set --resource-group az-container-book \
            --name az-container-book-app --slot slot1 \
            --docker-custom-image-name azcontainerbookacr.azurecr.io/todolist:v1.0.0-tem_17.0.4_8-jre-alpine_$GITHUB_SHA 